/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventario;

/**
 *
 * @author LENOVO
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReporte = new javax.swing.JButton();
        btnIngreso = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        btnRegistro1 = new javax.swing.JButton();
        btnRegistro2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnReporte.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        btnReporte.setText("REPORTES");
        btnReporte.addActionListener(this::btnReporteActionPerformed);

        btnIngreso.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        btnIngreso.setText("INGRESOS");
        btnIngreso.addActionListener(this::btnIngresoActionPerformed);

        btnSalida.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        btnSalida.setText("SALIDAS");
        btnSalida.addActionListener(this::btnSalidaActionPerformed);

        btnRegistro.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        btnRegistro.setText("NEW USER");
        btnRegistro.addActionListener(this::btnRegistroActionPerformed);

        btnRegistro1.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        btnRegistro1.setText("NEW PRODUCT");
        btnRegistro1.addActionListener(this::btnRegistro1ActionPerformed);

        btnRegistro2.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        btnRegistro2.setText("NEW STUDENT");
        btnRegistro2.addActionListener(this::btnRegistro2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistro2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(btnIngreso)
                .addGap(18, 18, 18)
                .addComponent(btnSalida)
                .addGap(18, 18, 18)
                .addComponent(btnRegistro1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistro)
                .addGap(18, 18, 18)
                .addComponent(btnRegistro2)
                .addGap(18, 18, 18)
                .addComponent(btnReporte)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
 RegistrarUsuarios ru = new RegistrarUsuarios();
    ru.setVisible(true);

    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistro1ActionPerformed
 RegistrarProducto rp = new RegistrarProducto();
    rp.setVisible(true);

    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistro1ActionPerformed

    private void btnRegistro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistro2ActionPerformed
 NuevoEstudiante ne = new NuevoEstudiante();
    ne.setVisible(true);

    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistro2ActionPerformed

    private void btnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoActionPerformed
 Ingresos ing = new Ingresos();
    ing.setVisible(true);

    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresoActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
 Salidas salida = new Salidas();
    salida.setVisible(true);

    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
 Reportes crm = new Reportes();
    crm.setVisible(true);

    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngreso;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnRegistro1;
    private javax.swing.JButton btnRegistro2;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalida;
    // End of variables declaration//GEN-END:variables
}
